### ISSUE TITLE
投稿にいいねを押すとpostIdが読み込めないエラーが発生する

### ISSUE THREAD

**Issue by gigi434** [gigi434/real-sns-ex-facebook#24]
# 問題
postコンポーネントのいいね機能に対してtrue/falseを設定すると検証ツールにて下記エラーが出現する
<details>
<summary>エラー内容</summary>
<pre>
<code>
TypeError: Cannot read properties of undefined (reading 'postId')
    at Auth.js:70:1
    at jsx-runtime.js:7:1
    at Object.dispatch (immutableStateInvariantMiddleware.ts:208:1)
    at dispatch (<anonymous>:3665:80)
    at handleLike (Post.jsx:32:1)
    at onClick (Post.jsx:62:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4134:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4184:1)
    at invokeGuardedCallback (react-dom.development.js:4247:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4263:1)
</pre>
</code>
</details>

# 解決方法
 - postコンポーネントのいいね機能に関してはAuth.jsは関与していないはずなので、ユーザー管理機能の見直しを含めてエラーログからAuth.jsとPost.jsを確認する

**Comment by gigi434** [comment]
マージが完了したしたためクローズ
